/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: k8s.io/kubernetes/vendor/k8s.io/api/global-resource-service/resource-management/pkg/common-lib/types/generated.proto

package types

import (
	fmt "fmt"

	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"

	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_sortkeys "github.com/gogo/protobuf/sortkeys"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func (m *LogicalNode) Reset()      { *m = LogicalNode{} }
func (*LogicalNode) ProtoMessage() {}
func (*LogicalNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e6ff26d2a95106f, []int{0}
}
func (m *LogicalNode) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LogicalNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *LogicalNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogicalNode.Merge(m, src)
}
func (m *LogicalNode) XXX_Size() int {
	return m.Size()
}
func (m *LogicalNode) XXX_DiscardUnknown() {
	xxx_messageInfo_LogicalNode.DiscardUnknown(m)
}

var xxx_messageInfo_LogicalNode proto.InternalMessageInfo

func (m *NodeEvent) Reset()      { *m = NodeEvent{} }
func (*NodeEvent) ProtoMessage() {}
func (*NodeEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e6ff26d2a95106f, []int{1}
}
func (m *NodeEvent) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NodeEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *NodeEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeEvent.Merge(m, src)
}
func (m *NodeEvent) XXX_Size() int {
	return m.Size()
}
func (m *NodeEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeEvent.DiscardUnknown(m)
}

var xxx_messageInfo_NodeEvent proto.InternalMessageInfo

func (m *NodeGeoInfo) Reset()      { *m = NodeGeoInfo{} }
func (*NodeGeoInfo) ProtoMessage() {}
func (*NodeGeoInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e6ff26d2a95106f, []int{2}
}
func (m *NodeGeoInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NodeGeoInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *NodeGeoInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeGeoInfo.Merge(m, src)
}
func (m *NodeGeoInfo) XXX_Size() int {
	return m.Size()
}
func (m *NodeGeoInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeGeoInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NodeGeoInfo proto.InternalMessageInfo

func (m *NodeResource) Reset()      { *m = NodeResource{} }
func (*NodeResource) ProtoMessage() {}
func (*NodeResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e6ff26d2a95106f, []int{3}
}
func (m *NodeResource) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NodeResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *NodeResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeResource.Merge(m, src)
}
func (m *NodeResource) XXX_Size() int {
	return m.Size()
}
func (m *NodeResource) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeResource.DiscardUnknown(m)
}

var xxx_messageInfo_NodeResource proto.InternalMessageInfo

func (m *NodeSpecialHardWareTypeInfo) Reset()      { *m = NodeSpecialHardWareTypeInfo{} }
func (*NodeSpecialHardWareTypeInfo) ProtoMessage() {}
func (*NodeSpecialHardWareTypeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e6ff26d2a95106f, []int{4}
}
func (m *NodeSpecialHardWareTypeInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NodeSpecialHardWareTypeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *NodeSpecialHardWareTypeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeSpecialHardWareTypeInfo.Merge(m, src)
}
func (m *NodeSpecialHardWareTypeInfo) XXX_Size() int {
	return m.Size()
}
func (m *NodeSpecialHardWareTypeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeSpecialHardWareTypeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NodeSpecialHardWareTypeInfo proto.InternalMessageInfo

func (m *NodeTaints) Reset()      { *m = NodeTaints{} }
func (*NodeTaints) ProtoMessage() {}
func (*NodeTaints) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e6ff26d2a95106f, []int{5}
}
func (m *NodeTaints) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NodeTaints) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *NodeTaints) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeTaints.Merge(m, src)
}
func (m *NodeTaints) XXX_Size() int {
	return m.Size()
}
func (m *NodeTaints) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeTaints.DiscardUnknown(m)
}

var xxx_messageInfo_NodeTaints proto.InternalMessageInfo

func (m *ResponseFromRRM) Reset()      { *m = ResponseFromRRM{} }
func (*ResponseFromRRM) ProtoMessage() {}
func (*ResponseFromRRM) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e6ff26d2a95106f, []int{6}
}
func (m *ResponseFromRRM) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ResponseFromRRM) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *ResponseFromRRM) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseFromRRM.Merge(m, src)
}
func (m *ResponseFromRRM) XXX_Size() int {
	return m.Size()
}
func (m *ResponseFromRRM) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseFromRRM.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseFromRRM proto.InternalMessageInfo

func (m *RpNodeEvents) Reset()      { *m = RpNodeEvents{} }
func (*RpNodeEvents) ProtoMessage() {}
func (*RpNodeEvents) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e6ff26d2a95106f, []int{7}
}
func (m *RpNodeEvents) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RpNodeEvents) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *RpNodeEvents) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpNodeEvents.Merge(m, src)
}
func (m *RpNodeEvents) XXX_Size() int {
	return m.Size()
}
func (m *RpNodeEvents) XXX_DiscardUnknown() {
	xxx_messageInfo_RpNodeEvents.DiscardUnknown(m)
}

var xxx_messageInfo_RpNodeEvents proto.InternalMessageInfo

func (m *Time) Reset()      { *m = Time{} }
func (*Time) ProtoMessage() {}
func (*Time) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e6ff26d2a95106f, []int{8}
}
func (m *Time) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Time.Unmarshal(m, b)
}
func (m *Time) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Time.Marshal(b, m, deterministic)
}
func (m *Time) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Time.Merge(m, src)
}
func (m *Time) XXX_Size() int {
	return xxx_messageInfo_Time.Size(m)
}
func (m *Time) XXX_DiscardUnknown() {
	xxx_messageInfo_Time.DiscardUnknown(m)
}

var xxx_messageInfo_Time proto.InternalMessageInfo

func (m *Timestamp) Reset()      { *m = Timestamp{} }
func (*Timestamp) ProtoMessage() {}
func (*Timestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e6ff26d2a95106f, []int{9}
}
func (m *Timestamp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Timestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *Timestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Timestamp.Merge(m, src)
}
func (m *Timestamp) XXX_Size() int {
	return m.Size()
}
func (m *Timestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_Timestamp.DiscardUnknown(m)
}

var xxx_messageInfo_Timestamp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*LogicalNode)(nil), "k8s.io.api.global_resource_service.resource_management.pkg.common_lib.types.LogicalNode")
	proto.RegisterType((*NodeEvent)(nil), "k8s.io.api.global_resource_service.resource_management.pkg.common_lib.types.NodeEvent")
	proto.RegisterType((*NodeGeoInfo)(nil), "k8s.io.api.global_resource_service.resource_management.pkg.common_lib.types.NodeGeoInfo")
	proto.RegisterType((*NodeResource)(nil), "k8s.io.api.global_resource_service.resource_management.pkg.common_lib.types.NodeResource")
	proto.RegisterMapType((map[ResourceName]int64)(nil), "k8s.io.api.global_resource_service.resource_management.pkg.common_lib.types.NodeResource.ScalarResourcesEntry")
	proto.RegisterType((*NodeSpecialHardWareTypeInfo)(nil), "k8s.io.api.global_resource_service.resource_management.pkg.common_lib.types.NodeSpecialHardWareTypeInfo")
	proto.RegisterType((*NodeTaints)(nil), "k8s.io.api.global_resource_service.resource_management.pkg.common_lib.types.NodeTaints")
	proto.RegisterType((*ResponseFromRRM)(nil), "k8s.io.api.global_resource_service.resource_management.pkg.common_lib.types.ResponseFromRRM")
	proto.RegisterType((*RpNodeEvents)(nil), "k8s.io.api.global_resource_service.resource_management.pkg.common_lib.types.RpNodeEvents")
	proto.RegisterType((*Time)(nil), "k8s.io.api.global_resource_service.resource_management.pkg.common_lib.types.Time")
	proto.RegisterType((*Timestamp)(nil), "k8s.io.api.global_resource_service.resource_management.pkg.common_lib.types.Timestamp")
}

func init() {
	proto.RegisterFile("k8s.io/kubernetes/vendor/k8s.io/api/global-resource-service/resource-management/pkg/common-lib/types/generated.proto", fileDescriptor_0e6ff26d2a95106f)
}

var fileDescriptor_0e6ff26d2a95106f = []byte{
	// 1337 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xbf, 0x6f, 0x1b, 0xc7,
	0x12, 0xe6, 0x91, 0xa2, 0x44, 0x2e, 0xf5, 0x4c, 0x6a, 0xcd, 0xf7, 0x1e, 0x23, 0x07, 0xa4, 0xc0,
	0x04, 0x8e, 0x9c, 0x44, 0x47, 0x5b, 0x31, 0x02, 0xc3, 0x55, 0x74, 0xb2, 0x64, 0x1b, 0xb1, 0x04,
	0x61, 0xe5, 0x1f, 0x89, 0x53, 0x1c, 0x96, 0x77, 0xab, 0xe3, 0x41, 0x77, 0xbb, 0x87, 0xdd, 0x23,
	0x1d, 0xba, 0x89, 0x11, 0x04, 0x48, 0x4a, 0x97, 0x2e, 0xad, 0x32, 0x4d, 0xda, 0x34, 0xa9, 0x52,
	0xb9, 0x74, 0xe9, 0x22, 0x60, 0x62, 0xe6, 0xbf, 0x10, 0x10, 0x23, 0xd8, 0xbd, 0xbd, 0x23, 0x4d,
	0x1b, 0xa9, 0x98, 0x6e, 0xf7, 0xfb, 0x66, 0x67, 0xbe, 0x9b, 0x9d, 0x99, 0x3d, 0x10, 0x1f, 0x5f,
	0x11, 0xa6, 0xcf, 0x3a, 0xc7, 0xfd, 0x2e, 0xe1, 0x94, 0xc4, 0x44, 0x74, 0x06, 0x84, 0xba, 0x8c,
	0x77, 0x34, 0x81, 0x23, 0xbf, 0xe3, 0x05, 0xac, 0x8b, 0x83, 0x0d, 0x4e, 0x04, 0xeb, 0x73, 0x87,
	0x6c, 0x08, 0xc2, 0x07, 0xbe, 0x43, 0x3a, 0x19, 0x10, 0x62, 0x8a, 0x3d, 0x12, 0x12, 0x1a, 0x77,
	0xa2, 0x63, 0xaf, 0xe3, 0xb0, 0x30, 0x64, 0x74, 0x23, 0xf0, 0xbb, 0x9d, 0x78, 0x18, 0x11, 0xd1,
	0xf1, 0x08, 0x25, 0x1c, 0xc7, 0xc4, 0x35, 0x23, 0xce, 0x62, 0x06, 0x3f, 0x4f, 0x9c, 0x9b, 0x38,
	0xf2, 0xcd, 0xc4, 0xb9, 0x9d, 0xfa, 0xb2, 0xb5, 0x73, 0x33, 0x03, 0x26, 0xce, 0xcd, 0xe8, 0xd8,
	0x33, 0x13, 0xe7, 0x76, 0xe0, 0x77, 0x4d, 0xe5, 0x7c, 0x75, 0xc3, 0xf3, 0xe3, 0x5e, 0xbf, 0x2b,
	0x89, 0x8e, 0xc7, 0x3c, 0xd6, 0x51, 0x31, 0xba, 0xfd, 0x23, 0xb5, 0x53, 0x1b, 0xb5, 0x4a, 0x62,
	0xaf, 0x5e, 0x9e, 0x7c, 0x58, 0x88, 0x9d, 0x9e, 0x4f, 0x09, 0x1f, 0x2a, 0xd5, 0x38, 0xf2, 0x45,
	0x27, 0x24, 0x31, 0xee, 0x0c, 0x2e, 0xcd, 0x2a, 0x6e, 0xbf, 0x5a, 0x02, 0x95, 0x5b, 0xcc, 0xf3,
	0x1d, 0x1c, 0xec, 0x33, 0x97, 0xc0, 0x55, 0x90, 0xf7, 0xdd, 0x86, 0xb1, 0x66, 0xac, 0x97, 0x2d,
	0xf0, 0x6c, 0xd4, 0xca, 0x8d, 0x47, 0xad, 0xfc, 0x4d, 0x17, 0xe5, 0x7d, 0x17, 0x5a, 0xa0, 0x96,
	0x89, 0x1f, 0x10, 0x2e, 0x7c, 0x46, 0x1b, 0x79, 0x65, 0xf9, 0x7f, 0x6d, 0x59, 0x45, 0x9a, 0xbf,
	0x9b, 0xd0, 0xa8, 0xca, 0x5f, 0x07, 0xe0, 0x77, 0x06, 0x28, 0x79, 0x84, 0xd9, 0x3e, 0x3d, 0x62,
	0x8d, 0xc2, 0x9a, 0xb1, 0x5e, 0xd9, 0xfc, 0xc2, 0x9c, 0x63, 0xd6, 0x4c, 0xf9, 0x15, 0xd7, 0x09,
	0xbb, 0x49, 0x8f, 0x98, 0x55, 0xd5, 0xb2, 0x96, 0x34, 0x80, 0x96, 0xbc, 0x64, 0x01, 0xbf, 0x01,
	0x8b, 0x31, 0xf6, 0x69, 0x2c, 0x1a, 0x0b, 0x4a, 0xc3, 0xbd, 0xb9, 0x6b, 0xb8, 0xad, 0xdc, 0x5b,
	0x67, 0xb4, 0x84, 0xc5, 0x64, 0x8f, 0x74, 0x58, 0xf8, 0x8b, 0x01, 0xfe, 0x27, 0x22, 0xe2, 0xf8,
	0x38, 0xb0, 0x7b, 0x98, 0xbb, 0x0f, 0x30, 0x27, 0xb6, 0x3a, 0xdd, 0x28, 0x2a, 0x45, 0xbd, 0xb9,
	0x2b, 0x3a, 0x4c, 0xc2, 0xdd, 0xc0, 0xdc, 0xbd, 0x87, 0x39, 0xb9, 0x3d, 0x8c, 0x88, 0xca, 0xd2,
	0xbb, 0x5a, 0x62, 0x7d, 0xca, 0xe0, 0x81, 0x36, 0x10, 0xa8, 0x2e, 0xde, 0x82, 0xc2, 0x1f, 0x0d,
	0x50, 0xc7, 0x41, 0xc0, 0x1c, 0x1c, 0xe3, 0x6e, 0x40, 0x32, 0x65, 0x8d, 0x45, 0x25, 0xfe, 0xcb,
	0xb9, 0x8b, 0x4f, 0x0b, 0xcb, 0x3a, 0xa7, 0xd5, 0x9e, 0xdd, 0x9a, 0x84, 0x4f, 0x49, 0x74, 0x16,
	0xbf, 0x09, 0xc2, 0x4d, 0x00, 0x1c, 0x46, 0x5d, 0x3f, 0xf6, 0x19, 0x15, 0x8d, 0xa5, 0x35, 0x63,
	0xbd, 0x68, 0x41, 0xed, 0x05, 0x6c, 0x67, 0x0c, 0x9a, 0xb2, 0x82, 0x1f, 0x83, 0x12, 0x27, 0x52,
	0x28, 0x71, 0x1b, 0xa5, 0x35, 0x63, 0xbd, 0x64, 0xd5, 0xf4, 0x89, 0x12, 0xd2, 0x38, 0xca, 0x2c,
	0xe0, 0x4d, 0xb0, 0xac, 0x5b, 0x4e, 0x5d, 0x61, 0xa3, 0xac, 0x9a, 0xe2, 0xbc, 0x3e, 0x51, 0xd9,
	0x4b, 0x38, 0x99, 0xb9, 0xd3, 0x51, 0xab, 0x2a, 0x3f, 0x67, 0x0a, 0x42, 0x95, 0x70, 0xb2, 0x81,
	0x0c, 0xac, 0x04, 0x58, 0xc4, 0x76, 0x3f, 0x72, 0x65, 0x97, 0xda, 0xb1, 0x1f, 0x92, 0x06, 0x50,
	0x49, 0xfd, 0x70, 0x2a, 0xa9, 0x59, 0x87, 0xab, 0x8c, 0xc9, 0x0e, 0x37, 0x65, 0x87, 0x9b, 0x83,
	0x4b, 0xe6, 0x6d, 0x3f, 0x24, 0x93, 0x86, 0xbc, 0x85, 0x45, 0x7c, 0x27, 0xf1, 0x25, 0x09, 0x54,
	0x0d, 0x5e, 0x07, 0xda, 0x3f, 0x19, 0xa0, 0x2c, 0x15, 0xed, 0x0c, 0x08, 0x8d, 0xe1, 0x85, 0xa9,
	0xf6, 0x7f, 0x47, 0xfb, 0x58, 0xd0, 0xc2, 0xcb, 0xca, 0x44, 0x49, 0x96, 0xd3, 0x60, 0x00, 0x16,
	0x28, 0x73, 0x89, 0x9a, 0x00, 0xf3, 0x6e, 0xe2, 0xa9, 0x89, 0x64, 0x95, 0xa4, 0x04, 0x55, 0x02,
	0x2a, 0x5e, 0xfb, 0xe7, 0x3c, 0xa8, 0x4c, 0x35, 0x39, 0xbc, 0x0c, 0x16, 0x39, 0xf1, 0xe4, 0x2c,
	0x92, 0xb2, 0x0b, 0x59, 0x39, 0x2f, 0x22, 0x85, 0x9e, 0x8e, 0x5a, 0x20, 0x59, 0xed, 0xe3, 0x90,
	0x20, 0x6d, 0x0b, 0x2d, 0x90, 0xe7, 0x91, 0xd2, 0x5e, 0xb0, 0x36, 0xf5, 0x89, 0x95, 0xb4, 0x64,
	0x0e, 0x30, 0x8f, 0x55, 0x21, 0x9c, 0x8e, 0x5a, 0xff, 0x7d, 0x03, 0x54, 0x7e, 0xf2, 0x3c, 0x82,
	0x97, 0x41, 0xde, 0x75, 0xd4, 0x10, 0x2b, 0x5b, 0xef, 0xa7, 0x05, 0x75, 0x0d, 0xc7, 0x78, 0x9b,
	0xd0, 0x98, 0xf0, 0xd3, 0x51, 0xeb, 0xcc, 0x64, 0x97, 0x9c, 0x72, 0x1d, 0xf8, 0x19, 0xc8, 0xe3,
	0x87, 0x6a, 0xec, 0x94, 0xad, 0x8b, 0xfa, 0x54, 0x6d, 0x6b, 0x80, 0xfd, 0x00, 0x77, 0xfd, 0xc0,
	0x8f, 0x87, 0xf7, 0x19, 0x95, 0xe9, 0xae, 0xcf, 0x62, 0x89, 0x07, 0xfc, 0x10, 0x7e, 0x0a, 0xf2,
	0x47, 0xae, 0x1a, 0x13, 0x53, 0x45, 0xb6, 0x8b, 0xfb, 0x41, 0x7c, 0x8d, 0x85, 0xd8, 0x97, 0xaa,
	0xab, 0x53, 0xdb, 0xe4, 0xdc, 0x91, 0xdb, 0xfe, 0xab, 0x00, 0x96, 0xa7, 0x7b, 0x09, 0x6e, 0x80,
	0x72, 0xe8, 0x07, 0x81, 0x6f, 0x3b, 0x51, 0x5f, 0x67, 0x2f, 0x2b, 0xf3, 0x3d, 0x49, 0x6c, 0x1f,
	0xdc, 0x41, 0x25, 0x65, 0xb2, 0x1d, 0xf5, 0xe1, 0x79, 0xb0, 0x18, 0x92, 0x90, 0xf1, 0xa1, 0xce,
	0x5b, 0x36, 0xdb, 0xf6, 0x14, 0x8a, 0x34, 0x0b, 0x77, 0xc0, 0x0a, 0x89, 0x7a, 0x24, 0x24, 0x1c,
	0x07, 0xb6, 0x88, 0x19, 0xc7, 0x1e, 0x51, 0x69, 0x2a, 0x58, 0x8d, 0xf4, 0x83, 0x77, 0x52, 0x83,
	0xc3, 0x84, 0x47, 0x35, 0x32, 0x83, 0xc0, 0x5d, 0x00, 0x65, 0x3b, 0x3f, 0x20, 0xae, 0x1d, 0x31,
	0xd7, 0xa6, 0xfd, 0xb0, 0x4b, 0xb8, 0x4a, 0x5c, 0x71, 0xe2, 0x67, 0x2b, 0xb1, 0x38, 0x60, 0xee,
	0xbe, 0xe2, 0x51, 0x0d, 0xcf, 0x20, 0xf0, 0x57, 0x03, 0xd4, 0x84, 0x83, 0x03, 0xcc, 0xb3, 0x8a,
	0x94, 0x43, 0xb6, 0xb0, 0x5e, 0xd9, 0xa4, 0xff, 0xda, 0x9c, 0x32, 0x0f, 0x55, 0xc4, 0x74, 0x2b,
	0x76, 0x68, 0xcc, 0x87, 0xd6, 0x07, 0x69, 0x5b, 0xce, 0xb0, 0xdf, 0xfe, 0xde, 0x5a, 0x4e, 0x37,
	0xea, 0xba, 0xaa, 0xe2, 0x75, 0x83, 0x55, 0x0b, 0xd4, 0xdf, 0xe6, 0x11, 0xd6, 0x40, 0xe1, 0x98,
	0x0c, 0x93, 0x8e, 0x45, 0x72, 0x09, 0xeb, 0xa0, 0x38, 0xc0, 0x41, 0x3f, 0x69, 0xcc, 0x02, 0x4a,
	0x36, 0x57, 0xf3, 0x57, 0x8c, 0x76, 0x04, 0xce, 0xfd, 0xc3, 0x3b, 0x20, 0xaf, 0xb7, 0x87, 0x85,
	0xa7, 0x4b, 0xa1, 0x34, 0xb9, 0xde, 0x1b, 0x58, 0x5c, 0x8f, 0xfa, 0x48, 0xb3, 0xf0, 0x02, 0x58,
	0xea, 0x61, 0x71, 0x14, 0x79, 0x58, 0x85, 0x28, 0x4d, 0x9e, 0xd9, 0x1b, 0x58, 0xec, 0x1e, 0x5c,
	0xdf, 0x42, 0x29, 0xdf, 0x16, 0x00, 0x4c, 0xde, 0x42, 0xf8, 0x09, 0xa8, 0x50, 0x66, 0x0b, 0xa7,
	0x47, 0xdc, 0x7e, 0x40, 0x74, 0x94, 0x6c, 0x12, 0xef, 0xb3, 0x43, 0xcd, 0x20, 0x40, 0xb3, 0x35,
	0xbc, 0x08, 0x00, 0x65, 0x36, 0xf9, 0x9a, 0x38, 0xfd, 0x98, 0xe8, 0x80, 0x2b, 0xfa, 0x4c, 0x79,
	0x9f, 0xed, 0x24, 0x04, 0x2a, 0xd3, 0x74, 0xd9, 0x7e, 0x65, 0x00, 0xf9, 0x1f, 0x12, 0x31, 0x2a,
	0xc8, 0x2e, 0x67, 0x21, 0x42, 0x7b, 0xf0, 0xc4, 0x00, 0x30, 0xe9, 0x7c, 0x5b, 0x0e, 0x11, 0x9b,
	0xc8, 0x51, 0x26, 0x1a, 0x86, 0xaa, 0x82, 0xf9, 0xbe, 0x56, 0x28, 0xca, 0xc6, 0xa9, 0x98, 0xd4,
	0xa9, 0x1e, 0x41, 0x19, 0x83, 0x6a, 0x7c, 0x06, 0x81, 0x2d, 0x50, 0xe4, 0x83, 0x10, 0x27, 0x53,
	0x69, 0xd9, 0x2a, 0x8f, 0x47, 0xad, 0x22, 0x1a, 0xec, 0xe1, 0x08, 0x25, 0xb8, 0xbc, 0xa0, 0x80,
	0x50, 0x2f, 0xee, 0xa9, 0x66, 0x5a, 0x98, 0x5c, 0xd0, 0x2d, 0x85, 0x22, 0xcd, 0xb6, 0x9f, 0x18,
	0x60, 0x79, 0x5a, 0x05, 0xfc, 0xde, 0x90, 0x99, 0x9f, 0xfd, 0xec, 0xbb, 0x73, 0x2f, 0x7e, 0x15,
	0xce, 0x3a, 0x93, 0xdc, 0x66, 0xf6, 0xa5, 0x80, 0x66, 0xeb, 0x76, 0x00, 0x16, 0xe4, 0xab, 0x23,
	0x6b, 0x48, 0x10, 0xf9, 0xde, 0x0a, 0x3d, 0x77, 0xb2, 0x1a, 0x3a, 0x4c, 0x60, 0x94, 0xf2, 0xf0,
	0x3d, 0x50, 0xa4, 0x98, 0x32, 0xa1, 0xd2, 0x52, 0xb4, 0xfe, 0xa3, 0x0d, 0x8b, 0xfb, 0x12, 0x44,
	0x09, 0x77, 0xb5, 0xfe, 0xe4, 0x69, 0x2b, 0xf7, 0xc3, 0x49, 0x2b, 0xf7, 0xf8, 0xa4, 0x95, 0x7b,
	0x7a, 0xd2, 0xca, 0x3d, 0xfa, 0x6d, 0x2d, 0xd7, 0xfe, 0x0a, 0x94, 0x65, 0x34, 0x11, 0xe3, 0x30,
	0x9a, 0x77, 0x48, 0xeb, 0xa3, 0x67, 0x2f, 0x9b, 0xb9, 0xe7, 0x2f, 0x9b, 0xb9, 0x17, 0x2f, 0x9b,
	0xb9, 0x47, 0xe3, 0xa6, 0xf1, 0x6c, 0xdc, 0x34, 0x9e, 0x8f, 0x9b, 0xc6, 0x8b, 0x71, 0xd3, 0xf8,
	0x63, 0xdc, 0x34, 0x1e, 0xff, 0xd9, 0xcc, 0xdd, 0x2f, 0xaa, 0xec, 0xfc, 0x1d, 0x00, 0x00, 0xff,
	0xff, 0xc9, 0x24, 0x0c, 0x63, 0x8f, 0x0c, 0x00, 0x00,
}

func (m *LogicalNode) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LogicalNode) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LogicalNode) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.LastUpdatedTime.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x52
	i -= len(m.MachineType)
	copy(dAtA[i:], m.MachineType)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.MachineType)))
	i--
	dAtA[i] = 0x4a
	i--
	if m.Reserved {
		dAtA[i] = 1
	} else {
		dAtA[i] = 0
	}
	i--
	dAtA[i] = 0x40
	i = encodeVarintGenerated(dAtA, i, uint64(m.Conditions))
	i--
	dAtA[i] = 0x38
	{
		size, err := m.AllocatableResource.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size, err := m.SpecialHardwareTypes.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size, err := m.Taints.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size, err := m.GeoInfo.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	i -= len(m.ResourceVersion)
	copy(dAtA[i:], m.ResourceVersion)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.ResourceVersion)))
	i--
	dAtA[i] = 0x12
	i -= len(m.Id)
	copy(dAtA[i:], m.Id)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Id)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *NodeEvent) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NodeEvent) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NodeEvent) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Node != nil {
		{
			size, err := m.Node.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenerated(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	i -= len(m.Type)
	copy(dAtA[i:], m.Type)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Type)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *NodeGeoInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NodeGeoInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NodeGeoInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i -= len(m.FaultDomain)
	copy(dAtA[i:], m.FaultDomain)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.FaultDomain)))
	i--
	dAtA[i] = 0x2a
	i -= len(m.AvailabilityZone)
	copy(dAtA[i:], m.AvailabilityZone)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.AvailabilityZone)))
	i--
	dAtA[i] = 0x22
	i -= len(m.DataCenter)
	copy(dAtA[i:], m.DataCenter)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.DataCenter)))
	i--
	dAtA[i] = 0x1a
	i = encodeVarintGenerated(dAtA, i, uint64(m.ResourcePartition))
	i--
	dAtA[i] = 0x10
	i = encodeVarintGenerated(dAtA, i, uint64(m.Region))
	i--
	dAtA[i] = 0x8
	return len(dAtA) - i, nil
}

func (m *NodeResource) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NodeResource) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NodeResource) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ScalarResources) > 0 {
		keysForScalarResources := make([]string, 0, len(m.ScalarResources))
		for k := range m.ScalarResources {
			keysForScalarResources = append(keysForScalarResources, string(k))
		}
		github_com_gogo_protobuf_sortkeys.Strings(keysForScalarResources)
		for iNdEx := len(keysForScalarResources) - 1; iNdEx >= 0; iNdEx-- {
			v := m.ScalarResources[ResourceName(keysForScalarResources[iNdEx])]
			baseI := i
			i = encodeVarintGenerated(dAtA, i, uint64(v))
			i--
			dAtA[i] = 0x10
			i -= len(keysForScalarResources[iNdEx])
			copy(dAtA[i:], keysForScalarResources[iNdEx])
			i = encodeVarintGenerated(dAtA, i, uint64(len(keysForScalarResources[iNdEx])))
			i--
			dAtA[i] = 0xa
			i = encodeVarintGenerated(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x2a
		}
	}
	i = encodeVarintGenerated(dAtA, i, uint64(m.AllowedPodNumber))
	i--
	dAtA[i] = 0x20
	i = encodeVarintGenerated(dAtA, i, uint64(m.EphemeralStorage))
	i--
	dAtA[i] = 0x18
	i = encodeVarintGenerated(dAtA, i, uint64(m.Memory))
	i--
	dAtA[i] = 0x10
	i = encodeVarintGenerated(dAtA, i, uint64(m.MilliCPU))
	i--
	dAtA[i] = 0x8
	return len(dAtA) - i, nil
}

func (m *NodeSpecialHardWareTypeInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NodeSpecialHardWareTypeInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NodeSpecialHardWareTypeInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i--
	if m.HasFPGA {
		dAtA[i] = 1
	} else {
		dAtA[i] = 0
	}
	i--
	dAtA[i] = 0x10
	i--
	if m.HasGpu {
		dAtA[i] = 1
	} else {
		dAtA[i] = 0
	}
	i--
	dAtA[i] = 0x8
	return len(dAtA) - i, nil
}

func (m *NodeTaints) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NodeTaints) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NodeTaints) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i--
	if m.NoExecute {
		dAtA[i] = 1
	} else {
		dAtA[i] = 0
	}
	i--
	dAtA[i] = 0x10
	i--
	if m.NoSchedule {
		dAtA[i] = 1
	} else {
		dAtA[i] = 0
	}
	i--
	dAtA[i] = 0x8
	return len(dAtA) - i, nil
}

func (m *ResponseFromRRM) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ResponseFromRRM) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ResponseFromRRM) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i = encodeVarintGenerated(dAtA, i, uint64(m.Length))
	i--
	dAtA[i] = 0x18
	if m.RvMap != nil {
		i -= len(m.RvMap)
		copy(dAtA[i:], m.RvMap)
		i = encodeVarintGenerated(dAtA, i, uint64(len(m.RvMap)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.RegionNodeEvents) > 0 {
		for iNdEx := len(m.RegionNodeEvents) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RegionNodeEvents[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenerated(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *RpNodeEvents) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RpNodeEvents) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RpNodeEvents) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NodeEvents) > 0 {
		for iNdEx := len(m.NodeEvents) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.NodeEvents[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenerated(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *Timestamp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Timestamp) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Timestamp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i = encodeVarintGenerated(dAtA, i, uint64(m.Nanos))
	i--
	dAtA[i] = 0x10
	i = encodeVarintGenerated(dAtA, i, uint64(m.Seconds))
	i--
	dAtA[i] = 0x8
	return len(dAtA) - i, nil
}

func encodeVarintGenerated(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenerated(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *LogicalNode) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.ResourceVersion)
	n += 1 + l + sovGenerated(uint64(l))
	l = m.GeoInfo.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Taints.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.SpecialHardwareTypes.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.AllocatableResource.Size()
	n += 1 + l + sovGenerated(uint64(l))
	n += 1 + sovGenerated(uint64(m.Conditions))
	n += 2
	l = len(m.MachineType)
	n += 1 + l + sovGenerated(uint64(l))
	l = m.LastUpdatedTime.Size()
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *NodeEvent) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Type)
	n += 1 + l + sovGenerated(uint64(l))
	if m.Node != nil {
		l = m.Node.Size()
		n += 1 + l + sovGenerated(uint64(l))
	}
	return n
}

func (m *NodeGeoInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovGenerated(uint64(m.Region))
	n += 1 + sovGenerated(uint64(m.ResourcePartition))
	l = len(m.DataCenter)
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.AvailabilityZone)
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.FaultDomain)
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *NodeResource) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovGenerated(uint64(m.MilliCPU))
	n += 1 + sovGenerated(uint64(m.Memory))
	n += 1 + sovGenerated(uint64(m.EphemeralStorage))
	n += 1 + sovGenerated(uint64(m.AllowedPodNumber))
	if len(m.ScalarResources) > 0 {
		for k, v := range m.ScalarResources {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovGenerated(uint64(len(k))) + 1 + sovGenerated(uint64(v))
			n += mapEntrySize + 1 + sovGenerated(uint64(mapEntrySize))
		}
	}
	return n
}

func (m *NodeSpecialHardWareTypeInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 2
	n += 2
	return n
}

func (m *NodeTaints) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 2
	n += 2
	return n
}

func (m *ResponseFromRRM) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.RegionNodeEvents) > 0 {
		for _, e := range m.RegionNodeEvents {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	if m.RvMap != nil {
		l = len(m.RvMap)
		n += 1 + l + sovGenerated(uint64(l))
	}
	n += 1 + sovGenerated(uint64(m.Length))
	return n
}

func (m *RpNodeEvents) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.NodeEvents) > 0 {
		for _, e := range m.NodeEvents {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	return n
}

func (m *Timestamp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovGenerated(uint64(m.Seconds))
	n += 1 + sovGenerated(uint64(m.Nanos))
	return n
}

func sovGenerated(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenerated(x uint64) (n int) {
	return sovGenerated(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *LogicalNode) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&LogicalNode{`,
		`Id:` + fmt.Sprintf("%v", this.Id) + `,`,
		`ResourceVersion:` + fmt.Sprintf("%v", this.ResourceVersion) + `,`,
		`GeoInfo:` + strings.Replace(strings.Replace(this.GeoInfo.String(), "NodeGeoInfo", "NodeGeoInfo", 1), `&`, ``, 1) + `,`,
		`Taints:` + strings.Replace(strings.Replace(this.Taints.String(), "NodeTaints", "NodeTaints", 1), `&`, ``, 1) + `,`,
		`SpecialHardwareTypes:` + strings.Replace(strings.Replace(this.SpecialHardwareTypes.String(), "NodeSpecialHardWareTypeInfo", "NodeSpecialHardWareTypeInfo", 1), `&`, ``, 1) + `,`,
		`AllocatableResource:` + strings.Replace(strings.Replace(this.AllocatableResource.String(), "NodeResource", "NodeResource", 1), `&`, ``, 1) + `,`,
		`Conditions:` + fmt.Sprintf("%v", this.Conditions) + `,`,
		`Reserved:` + fmt.Sprintf("%v", this.Reserved) + `,`,
		`MachineType:` + fmt.Sprintf("%v", this.MachineType) + `,`,
		`LastUpdatedTime:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.LastUpdatedTime), "Time", "v1.Time", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *NodeEvent) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&NodeEvent{`,
		`Type:` + fmt.Sprintf("%v", this.Type) + `,`,
		`Node:` + strings.Replace(this.Node.String(), "LogicalNode", "LogicalNode", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *NodeGeoInfo) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&NodeGeoInfo{`,
		`Region:` + fmt.Sprintf("%v", this.Region) + `,`,
		`ResourcePartition:` + fmt.Sprintf("%v", this.ResourcePartition) + `,`,
		`DataCenter:` + fmt.Sprintf("%v", this.DataCenter) + `,`,
		`AvailabilityZone:` + fmt.Sprintf("%v", this.AvailabilityZone) + `,`,
		`FaultDomain:` + fmt.Sprintf("%v", this.FaultDomain) + `,`,
		`}`,
	}, "")
	return s
}
func (this *NodeResource) String() string {
	if this == nil {
		return "nil"
	}
	keysForScalarResources := make([]string, 0, len(this.ScalarResources))
	for k := range this.ScalarResources {
		keysForScalarResources = append(keysForScalarResources, string(k))
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForScalarResources)
	mapStringForScalarResources := "map[ResourceName]int64{"
	for _, k := range keysForScalarResources {
		mapStringForScalarResources += fmt.Sprintf("%v: %v,", k, this.ScalarResources[ResourceName(k)])
	}
	mapStringForScalarResources += "}"
	s := strings.Join([]string{`&NodeResource{`,
		`MilliCPU:` + fmt.Sprintf("%v", this.MilliCPU) + `,`,
		`Memory:` + fmt.Sprintf("%v", this.Memory) + `,`,
		`EphemeralStorage:` + fmt.Sprintf("%v", this.EphemeralStorage) + `,`,
		`AllowedPodNumber:` + fmt.Sprintf("%v", this.AllowedPodNumber) + `,`,
		`ScalarResources:` + mapStringForScalarResources + `,`,
		`}`,
	}, "")
	return s
}
func (this *NodeSpecialHardWareTypeInfo) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&NodeSpecialHardWareTypeInfo{`,
		`HasGpu:` + fmt.Sprintf("%v", this.HasGpu) + `,`,
		`HasFPGA:` + fmt.Sprintf("%v", this.HasFPGA) + `,`,
		`}`,
	}, "")
	return s
}
func (this *NodeTaints) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&NodeTaints{`,
		`NoSchedule:` + fmt.Sprintf("%v", this.NoSchedule) + `,`,
		`NoExecute:` + fmt.Sprintf("%v", this.NoExecute) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ResponseFromRRM) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForRegionNodeEvents := "[]RpNodeEvents{"
	for _, f := range this.RegionNodeEvents {
		repeatedStringForRegionNodeEvents += strings.Replace(strings.Replace(f.String(), "RpNodeEvents", "RpNodeEvents", 1), `&`, ``, 1) + ","
	}
	repeatedStringForRegionNodeEvents += "}"
	s := strings.Join([]string{`&ResponseFromRRM{`,
		`RegionNodeEvents:` + repeatedStringForRegionNodeEvents + `,`,
		`RvMap:` + valueToStringGenerated(this.RvMap) + `,`,
		`Length:` + fmt.Sprintf("%v", this.Length) + `,`,
		`}`,
	}, "")
	return s
}
func (this *RpNodeEvents) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForNodeEvents := "[]*NodeEvent{"
	for _, f := range this.NodeEvents {
		repeatedStringForNodeEvents += strings.Replace(f.String(), "NodeEvent", "NodeEvent", 1) + ","
	}
	repeatedStringForNodeEvents += "}"
	s := strings.Join([]string{`&RpNodeEvents{`,
		`NodeEvents:` + repeatedStringForNodeEvents + `,`,
		`}`,
	}, "")
	return s
}
func (this *Timestamp) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Timestamp{`,
		`Seconds:` + fmt.Sprintf("%v", this.Seconds) + `,`,
		`Nanos:` + fmt.Sprintf("%v", this.Nanos) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringGenerated(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *LogicalNode) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LogicalNode: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LogicalNode: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResourceVersion", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ResourceVersion = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GeoInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.GeoInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Taints", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Taints.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SpecialHardwareTypes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SpecialHardwareTypes.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllocatableResource", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AllocatableResource.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Conditions", wireType)
			}
			m.Conditions = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Conditions |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reserved", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Reserved = bool(v != 0)
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MachineType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MachineType = NodeMachineType(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastUpdatedTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.LastUpdatedTime.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NodeEvent) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NodeEvent: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NodeEvent: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Type = EventType(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Node", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Node == nil {
				m.Node = &LogicalNode{}
			}
			if err := m.Node.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NodeGeoInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NodeGeoInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NodeGeoInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Region", wireType)
			}
			m.Region = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Region |= RegionName(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResourcePartition", wireType)
			}
			m.ResourcePartition = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ResourcePartition |= ResourcePartitionName(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DataCenter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DataCenter = DataCenterName(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AvailabilityZone", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AvailabilityZone = AvailabilityZoneName(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FaultDomain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FaultDomain = FaultDomainName(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NodeResource) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NodeResource: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NodeResource: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MilliCPU", wireType)
			}
			m.MilliCPU = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MilliCPU |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Memory", wireType)
			}
			m.Memory = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Memory |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EphemeralStorage", wireType)
			}
			m.EphemeralStorage = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EphemeralStorage |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowedPodNumber", wireType)
			}
			m.AllowedPodNumber = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AllowedPodNumber |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ScalarResources", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ScalarResources == nil {
				m.ScalarResources = make(map[ResourceName]int64)
			}
			var mapkey ResourceName
			var mapvalue int64
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGenerated
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGenerated
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthGenerated
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthGenerated
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = ResourceName(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGenerated
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapvalue |= int64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipGenerated(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthGenerated
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.ScalarResources[ResourceName(mapkey)] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NodeSpecialHardWareTypeInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NodeSpecialHardWareTypeInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NodeSpecialHardWareTypeInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HasGpu", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.HasGpu = bool(v != 0)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HasFPGA", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.HasFPGA = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NodeTaints) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NodeTaints: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NodeTaints: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NoSchedule", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.NoSchedule = bool(v != 0)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NoExecute", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.NoExecute = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ResponseFromRRM) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ResponseFromRRM: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ResponseFromRRM: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegionNodeEvents", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RegionNodeEvents = append(m.RegionNodeEvents, RpNodeEvents{})
			if err := m.RegionNodeEvents[len(m.RegionNodeEvents)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RvMap", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RvMap = append(m.RvMap[:0], dAtA[iNdEx:postIndex]...)
			if m.RvMap == nil {
				m.RvMap = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Length", wireType)
			}
			m.Length = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Length |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RpNodeEvents) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RpNodeEvents: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RpNodeEvents: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeEvents", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodeEvents = append(m.NodeEvents, &NodeEvent{})
			if err := m.NodeEvents[len(m.NodeEvents)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Timestamp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Timestamp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Timestamp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Seconds", wireType)
			}
			m.Seconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Seconds |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nanos", wireType)
			}
			m.Nanos = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nanos |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenerated(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenerated
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenerated
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenerated
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenerated        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenerated          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenerated = fmt.Errorf("proto: unexpected end of group")
)
